services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - './data:/data/db'
  cli:
    build: .
    stdin_open: true
    tty: true
    env_file:
      - .env